Js hangout categories
csci-499-sp23/team-6-sp23-redux pull request #60
Opened 2023-04-07 14:19 UTC by Kirazuto7

Changes:

CardDeck.js: Properly shuffles deck on first load. Passes parameters of hangout categories and location to api fetch function for more dynamic fetching. The hardcoded values will be replaced by user's preferences in the future.

HangoutService.js: Added a category to each data retrieved based on the search term to later sort favorited places. Also made the code more dynamic and concise. Requires a location and passed in array of categories to fetch data.

2023-04-07 14:34 UTC, chizy7 approved these changes
Looks good. Thank you for making the updates.

2023-04-07 14:34 UTC, chizy7 commented on my-app/src/Components/CardDeck.js
Changes here looks good. I noticed you addressed the workflow error from the previous merged code. Looks good.

2023-04-07 14:34 UTC, chizy7 commented on my-app/src/Services/HangoutService.js
This looks great too. I see you made updates from the previous suggestions. I don't have any further suggestions. 
This looks great and I think it is ready to be merged after review from other reviewers.

2023-04-07 14:35 UTC, chizy7 commented
I just noticed the workflow error after my review. That should be addressed first.

2023-04-07 20:43 UTC, caid4134 approved these changes
The error has been addressed now (line 61's "==" to "==="). We likely need another PR for re-deployment though for the workflow.

2023-04-08 01:14 UTC, JChen0915 requested changes
The changes to the code look good, but I hesitate to approve this when it does not deploy on github actions. Though this is simply the bot being very picky about usage of syntax in this case, if deployment fails it cannot be approved

2023-04-08 04:34 UTC, JChen0915 approved these changes
Followup to previous review, with more communication Jordan has established this is an issue with previews that has been fixed in a commit already, approved

2023-04-08 05:03 UTC, merged